/**
 * Question Bank — Data model and storage functions.
 *
 * Supports two modes:
 * - "ai_generated": Questions generated by the AI quiz pipeline
 * - "exact_source": Questions imported verbatim from a source document
 *
 * AI-generated questions and exact-source questions are stored in the same
 * localStorage key but are clearly differentiated by `importMode`.
 * Media assets for exact-source questions are stored separately in IndexedDB.
 */

import type { QuizQuestion, Difficulty, BloomLevel } from "../ai/schemas";
import type { ImportMode, ImportFidelity, QuestionMediaRef } from "./exact-import-types";

export type QuestionStatus =
  "draft" | "generated" | "validated" | "approved" | "rejected" | "archived";

export interface QuestionBankItem {
  id: string;

  // ---- Core Question Content ----
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  topic: string;
  difficulty: Difficulty;
  bloomLevel: BloomLevel;
  evidenceQuote?: string;

  // ---- Source Reference ----
  sourceDocumentName: string;
  sourceDocumentId?: string;
  sourcePage?: number;
  sourceSection?: string;
  sourceQuestionNumber?: number;

  // ---- Import Mode & Fidelity ----
  importMode: ImportMode;
  importFidelity?: ImportFidelity;

  /**
   * Verbatim question text from the source document.
   * ONLY set for exact_source mode. Immutable after import.
   */
  originalText?: string;

  /**
   * Full raw source block as extracted from the document.
   * Used for the "المصدر الأصلي" preview comparison.
   */
  sourceSnapshot?: string;

  /**
   * SHA-256 of sourceSnapshot.trim().
   * Proves source document integrity. Independent from canonicalQuestionHash.
   * @deprecated Use sourceRawHash
   */
  sourceHash?: string;

  /** SHA-256 of sourceSnapshot.trim() — canonical name */
  sourceRawHash?: string;

  /**
   * SHA-256 of canonicalizeQuestion({ questionText, options, correctIndex }).
   * Verified at render time to detect tampering.
   * @deprecated Use canonicalQuestionHash
   */
  questionHash?: string;

  /** SHA-256 of canonicalizeQuestion() — canonical name */
  canonicalQuestionHash?: string;

  /**
   * When true, the quiz MUST render originalText exactly.
   * Never re-generate or paraphrase.
   */
  renderSourceExactly?: boolean;

  /**
   * The raw correct answer as it appeared in the source.
   * e.g., "B", "ب", "(C)", "الخيار الثاني"
   */
  correctAnswerSource?: string;

  // ---- Extraction Metadata ----
  extractionConfidence?: number;
  requiresReview?: boolean;
  reviewReason?: string;
  mediaRequired?: boolean;
  mediaExtracted?: boolean;

  /**
   * References to media assets stored in IndexedDB.
   * Questions NEVER store Base64 data directly.
   */
  mediaRefs?: QuestionMediaRef[];

  // ---- Status & User Actions ----
  status: QuestionStatus;
  isVerified?: boolean;
  isSaved?: boolean;
  markedForReview?: boolean;

  /** Cumulative count of incorrect answers by the user */
  incorrectCount?: number;

  /** Cumulative count of correct answers by the user */
  correctCount?: number;

  createdAt: number;
  lastAttemptAt?: number;
  tags: string[];
}

export interface QuestionBankFilter {
  topic?: string;
  difficulty?: Difficulty;
  bloomLevel?: BloomLevel;
  status?: QuestionStatus;
  importMode?: ImportMode;
  importFidelity?: ImportFidelity;
  isSaved?: boolean;
  markedForReview?: boolean;
  hasErrors?: boolean; // incorrectCount > 0
  sourceDocumentId?: string;
  query?: string;
}

const STORAGE_KEY = "quizy_question_bank_v2";

// ---------------------------------------------------------------------------
// Filter
// ---------------------------------------------------------------------------

export function filterQuestionBank(
  items: QuestionBankItem[],
  filter: QuestionBankFilter,
): QuestionBankItem[] {
  return items.filter((item) => {
    if (filter.topic && item.topic !== filter.topic) return false;
    if (filter.difficulty && item.difficulty !== filter.difficulty) return false;
    if (filter.bloomLevel && item.bloomLevel !== filter.bloomLevel) return false;
    if (filter.status && item.status !== filter.status) return false;
    if (filter.importMode && item.importMode !== filter.importMode) return false;
    if (filter.importFidelity && item.importFidelity !== filter.importFidelity) return false;
    if (filter.isSaved !== undefined && !!item.isSaved !== filter.isSaved) return false;
    if (filter.markedForReview !== undefined && !!item.markedForReview !== filter.markedForReview)
      return false;
    if (filter.hasErrors && !(item.incorrectCount && item.incorrectCount > 0)) return false;
    if (filter.sourceDocumentId && item.sourceDocumentId !== filter.sourceDocumentId) return false;
    if (filter.query) {
      const q = filter.query.toLowerCase().trim();
      const matchesQuestion = item.question.toLowerCase().includes(q);
      const matchesTopic = item.topic.toLowerCase().includes(q);
      const matchesExplanation = item.explanation?.toLowerCase().includes(q) ?? false;
      const matchesOriginal = item.originalText?.toLowerCase().includes(q) ?? false;
      if (!matchesQuestion && !matchesTopic && !matchesExplanation && !matchesOriginal)
        return false;
    }
    return true;
  });
}

// ---------------------------------------------------------------------------
// Save AI-Generated Questions
// ---------------------------------------------------------------------------

export function saveQuestionsToBank(
  questions: QuizQuestion[],
  sourceDocumentName: string,
): QuestionBankItem[] {
  const existing = getStoredQuestionBank();
  const existingKeys = new Set(existing.map((item) => item.question.trim()));

  const newItems: QuestionBankItem[] = [];

  questions.forEach((q, idx) => {
    if (existingKeys.has(q.question.trim())) return;

    const item: QuestionBankItem = {
      id: `qb_ai_${Date.now()}_${idx}`,
      question: q.question,
      options: q.options,
      correctIndex: q.correctIndex,
      explanation: q.explanation,
      topic: q.topic,
      difficulty: q.difficulty,
      bloomLevel: q.bloomLevel || "understand",
      evidenceQuote: q.evidenceQuote,
      sourceDocumentName,
      importMode: "ai_generated",
      status: "validated",
      createdAt: Date.now(),
      tags: [q.topic, q.difficulty, q.bloomLevel || "understand"],
    };

    newItems.push(item);
    existingKeys.add(q.question.trim());
  });

  const updated = [...newItems, ...existing];
  persistBank(updated);
  return updated;
}

// ---------------------------------------------------------------------------
// Save Exact-Source Questions
// ---------------------------------------------------------------------------

import type { ImportedQuestion } from "./exact-import-types";

/**
 * Save exact-source questions from an import session to the question bank.
 * Only saves questions with importFidelity !== "failed".
 * Media assets must be saved to IndexedDB separately before calling this.
 */
export function saveExactSourceBank(importedQuestions: ImportedQuestion[]): QuestionBankItem[] {
  const existing = getStoredQuestionBank();
  const existingHashes = new Set(
    existing.map((item) => item.canonicalQuestionHash ?? item.questionHash).filter(Boolean),
  );

  const newItems: QuestionBankItem[] = [];

  importedQuestions.forEach((q, idx) => {
    if (q.importFidelity === "failed") return;
    if (q.canonicalQuestionHash && existingHashes.has(q.canonicalQuestionHash)) return;

    const item: QuestionBankItem = {
      id: `qb_exact_${Date.now()}_${idx}`,
      question: q.questionText,
      options: q.options,
      correctIndex: q.correctIndex,
      explanation: q.explanation ?? "",
      topic: q.topic ?? "غير محدد",
      difficulty: "medium",
      bloomLevel: "remember",

      sourceDocumentName: q.sourceDocumentName,
      sourceDocumentId: q.sourceDocumentId,
      sourcePage: q.sourcePage,
      sourceSection: q.sourceSection,
      sourceQuestionNumber: q.sourceQuestionNumber,

      importMode: "exact_source",
      importFidelity: q.importFidelity,

      originalText: q.originalText,
      sourceSnapshot: q.sourceSnapshot,
      sourceRawHash: q.sourceRawHash,
      sourceHash: q.sourceRawHash, // backward compat alias
      canonicalQuestionHash: q.canonicalQuestionHash,
      questionHash: q.canonicalQuestionHash, // backward compat alias
      renderSourceExactly: q.renderSourceExactly,
      correctAnswerSource: q.correctAnswerSource,

      extractionConfidence: q.extractionConfidence,
      requiresReview: q.requiresReview,
      reviewReason: q.reviewReason,
      mediaRequired: q.mediaRequired,
      mediaExtracted: q.mediaExtracted,
      mediaRefs: q.mediaRefs,

      status: q.isVerified ? "approved" : "validated",
      isVerified: q.isVerified,
      isSaved: false,
      markedForReview: q.requiresReview,

      createdAt: Date.now(),
      tags: [q.topic ?? "غير محدد", "exact_source"],
    };

    newItems.push(item);
    const newHash = q.canonicalQuestionHash;
    if (newHash) existingHashes.add(newHash);
  });

  const updated = [...newItems, ...existing];
  persistBank(updated);
  return updated;
}

// ---------------------------------------------------------------------------
// CRUD Operations
// ---------------------------------------------------------------------------

export function getStoredQuestionBank(): QuestionBankItem[] {
  if (typeof window === "undefined" || !window.localStorage) return [];
  try {
    // Support both legacy v1 key and new v2 key
    const raw = localStorage.getItem(STORAGE_KEY) ?? localStorage.getItem("quizy_question_bank_v1");
    if (!raw) return [];
    const parsed = JSON.parse(raw) as QuestionBankItem[];
    // Migrate legacy items without importMode
    return parsed.map((item) => ({
      ...item,
      importMode: item.importMode ?? "ai_generated",
    }));
  } catch {
    return [];
  }
}

function persistBank(items: QuestionBankItem[]): void {
  if (typeof window === "undefined" || !window.localStorage) return;
  try {
    // Cap at 300 items, newest first
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items.slice(0, 300)));
  } catch (e) {
    console.warn("Failed to persist question bank:", e);
  }
}

export function updateQuestionStatus(id: string, status: QuestionStatus): boolean {
  const items = getStoredQuestionBank();
  const target = items.find((i) => i.id === id);
  if (!target) return false;
  target.status = status;
  persistBank(items);
  return true;
}

/**
 * Update user-facing flags on a question (saved, review, verified).
 */
export function updateQuestionFlags(
  id: string,
  flags: Partial<Pick<QuestionBankItem, "isSaved" | "markedForReview" | "isVerified" | "status">>,
): boolean {
  const items = getStoredQuestionBank();
  const target = items.find((i) => i.id === id);
  if (!target) return false;
  Object.assign(target, flags);
  persistBank(items);
  return true;
}

/**
 * Track a question attempt and update correctCount / incorrectCount.
 */
export function trackQuestionAttempt(id: string, wasCorrect: boolean): void {
  const items = getStoredQuestionBank();
  const target = items.find((i) => i.id === id);
  if (!target) return;
  if (wasCorrect) {
    target.correctCount = (target.correctCount ?? 0) + 1;
  } else {
    target.incorrectCount = (target.incorrectCount ?? 0) + 1;
  }
  target.lastAttemptAt = Date.now();
  persistBank(items);
}

/**
 * Get all unique source document IDs in the question bank.
 */
export function getBankSourceDocuments(
  itemsList?: QuestionBankItem[],
): Array<{ id: string; name: string; count: number }> {
  const items = itemsList ?? getStoredQuestionBank();
  const docs = new Map<string, { id: string; name: string; count: number }>();

  for (const item of items) {
    if (item.sourceDocumentId) {
      const existing = docs.get(item.sourceDocumentId);
      if (existing) {
        existing.count++;
      } else {
        docs.set(item.sourceDocumentId, {
          id: item.sourceDocumentId,
          name: item.sourceDocumentName,
          count: 1,
        });
      }
    } else {
      // AI-generated without documentId — group by name
      const existing = docs.get(item.sourceDocumentName);
      if (existing) {
        existing.count++;
      } else {
        docs.set(item.sourceDocumentName, {
          id: item.sourceDocumentName,
          name: item.sourceDocumentName,
          count: 1,
        });
      }
    }
  }

  return Array.from(docs.values());
}

/**
 * Delete a question from the bank by ID.
 */
export function deleteQuestionFromBank(id: string): boolean {
  const items = getStoredQuestionBank();
  const idx = items.findIndex((i) => i.id === id);
  if (idx === -1) return false;
  items.splice(idx, 1);
  persistBank(items);
  return true;
}
